
name: main

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - id: Docker_meta
        name: Docker Metadata action
        uses: docker/metadata-action@v3.3.0
        with:
          images: rodesousa/helm-helper 
          tags: |
            type=semver
            type=sha
      - id: docker_meta_old
        name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        # compute tags:
        # - always tag with a short commit SHA : (arkhn/image:sha-${GITHUB_SHA::7})
        # - always tag with the branch same (replacing '/' with '-')
        # - when a tag follows semver (eg: v1.2.3), tag with 'latest' and '1.2.3'
        with:
          images: rodesousa/helm-helper
          tag-sha: true
          tag-semver: |
            {{version}}
      - id: run_1
        run: echo "${{ steps.docker_meta.outputs.version }} and ${{ steps.docker_meta.outputs.tags }} and ${{ steps.docker_meta.outputs.labels }}"
      - id: run_2
        run: echo "${{ steps.docker_meta_old.outputs.version }} and ${{ steps.docker_meta_old.outputs.tags }} and ${{ steps.docker_meta_old.outputs.labels }}"
